language: ruby
rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0 # The version of RVM installed on Travis doesn't yet recognise 2.3 as an alias of 2.3.0
notifications:
  email:
    - support@travellink.com.au
  flowdock:
    secure: D2Kf5l63amaHyf0WA5sVDLsB3dpSQpWrNYGgcqiKLPqBy/oG+bR93iuhe7e0FKKCImxGo3UyWor/QURbNi9tYI1uQTzWWA+UdF3m+dmBZEWoNDCWXGYGOaxDRCWNC0a5VGQXwNIAGqDNxvk8LxwFdqqX0KYPmyuVWbXvKlUf7mI=
