language: ruby
rvm:
  - 2.5
  - 2.6
  - 2.7
notifications:
  email:
    - support@travellink.com.au
  flowdock:
    secure: JUt4oMDS2rrSOzfb1VIDBBgl3Vox97PXAVc0mKjy8zvOQmTsfsGF6Eum85inEThjavm+WRmKffX66MjSSZ6wDWpaAmELh7LihQszJNhHejSfkSFJIc1v0AtrEoDpWEkh4bboO8eFMn+7Xw6ESZAzzK7k9791U9cuGShkFSnN76w=
sudo: false
cache: bundler
